var selectedText = "";
var selectedNode;
var annotations = [];
var annotation;
var startOffset;
var status;
var positionOfRewiever;
var conferences;
var userInfo;
var confs  = [];
var confN;
var articleN;
var annotationN;